// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoTS7r-uenVkROPVALlSF0U6kYmFwatLM',
    appId: '1:533350141352:web:0efbd61c6c69cfaa9b219d',
    messagingSenderId: '533350141352',
    projectId: 'mark-it-e1147',
    authDomain: 'mark-it-e1147.firebaseapp.com',
    storageBucket: 'mark-it-e1147.firebasestorage.app',
    measurementId: 'G-BM9KWNN4CH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSUisDILOgk-leUtoYnmdT0tp8Sm75zEc',
    appId: '1:533350141352:android:7c8b8a5a8a4004329b219d',
    messagingSenderId: '533350141352',
    projectId: 'mark-it-e1147',
    storageBucket: 'mark-it-e1147.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByTw89AmWjqt2tFK-XovN5LrrGcXy02oU',
    appId: '1:533350141352:ios:5563c3295059e3ef9b219d',
    messagingSenderId: '533350141352',
    projectId: 'mark-it-e1147',
    storageBucket: 'mark-it-e1147.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByTw89AmWjqt2tFK-XovN5LrrGcXy02oU',
    appId: '1:533350141352:ios:5563c3295059e3ef9b219d',
    messagingSenderId: '533350141352',
    projectId: 'mark-it-e1147',
    storageBucket: 'mark-it-e1147.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoTS7r-uenVkROPVALlSF0U6kYmFwatLM',
    appId: '1:533350141352:web:9d5b3456ef9a93ca9b219d',
    messagingSenderId: '533350141352',
    projectId: 'mark-it-e1147',
    authDomain: 'mark-it-e1147.firebaseapp.com',
    storageBucket: 'mark-it-e1147.firebasestorage.app',
    measurementId: 'G-63C71RQZHQ',
  );

}